### PR TITLE
implement ex01

### PR DESCRIPTION
**Pull request by ShockedMonkey**

### CODE REVIEW

**Review by josadcha — COMMENTED** [review]
though tests are successful, there is one warning message
Screenshot 2021-08-09 at 14 09 34
**0.75 points**

**Comment by josadcha** [comment]
@ShockedMonkey do you receive same info or is it my local issue?

**Comment by ShockedMonkey** [comment]
Hi! @josadcha!
I didn't change anything except the new file for implementation, so perhaps it means that your local pc doesn't have an alias for valgrind or it is not installed. It is just an assumption

**Comment by josadcha** [comment]
okay clear for me, thanks
then it's 1 point for this task

**Pull request merged**
