### PR TITLE
ex7 implement linked list (repushed)

### PR DESCRIPTION
**Pull request by ShockedMonkey**

### CODE REVIEW

**Comment by josadcha** [comment]
is it the right PR to check ex07? I have this error in tests:

Screenshot 2021-08-09 at 14 34 42

**Comment by ShockedMonkey** [comment]
@josadcha 
hm, yeah, this is a really strange place, it appears in`test.c` only, not in my impl file, maybe there should be "%p" in printf instead of "%s", cause `data` is a `void *`..
and I've just commented this line and forget about it, sorry :)

**Comment by josadcha** [comment]
yeah, with "%p" option tests are ok

**Comment by josadcha** [comment]
so you have 21/25 score because of missing ex08 task

**Pull request merged**
